### ISSUE TITLE
albert+crf或者albert+bilstm+crf

### ISSUE THREAD

**Issue by brealisty** [MarsRoger/albert_ner#6]
大神有什么有试过直接+crf和这个效果哪个更优秀一些呢？

**Comment by MarsRoger** [comment]
没有试过 你可以试一下，这个项目是我练手的第一个NLP项目 所以灭有过多深入

**Comment by MarsRoger** [comment]
> 大神有什么有试过直接+crf和这个效果哪个更优秀一些呢？

没有试过 你可以试一下，这个项目是我练手的第一个NLP项目 所以没有过多深入
