### ISSUE TITLE
你好，请问一下你的数据集是人民日报98年还是14年的

### ISSUE THREAD

**Issue by lijia2019310** [MarsRoger/albert_ner#7]

**Comment by MarsRoger** [comment]
这个数据集是 2007年 SIGHAN 评测使用的 MSRA（微软亚洲研究院）数据集，是2006年评测数据的子集。

**Comment by MarsRoger** [comment]
> _No description provided._

这个数据集是 2007年 SIGHAN 评测使用的 MSRA（微软亚洲研究院）数据集，是2006年评测数据的子集。

**Comment by lijia2019310** [comment]
> > _No description provided._
> 
> 这个数据集是 2007年 SIGHAN 评测使用的 MSRA（微软亚洲研究院）数据集，是2006年评测数据的子集。

好的，谢谢。
